# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 812acb02ea77a77e1887294d9f52006065607cbb254222c9bc2ce9a627d4c562e2741ecfe273c3f755060b394a21f0f5a3c632077d8157ae293b81b19d3cf8c3

test:
  secret_key_base: 05ccc4cee12555221cce50d4591969fe5846239af3615f99b53397ee99e32bcbe550ce13446056767ee7bf16389b1201ad4c9a40c5f40d37b17252454151f036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
